config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users do
    resources :items, only: [:create, :new, :destroy]
  end

  post 'items/create'
  get 'users/show'
  get 'welcome/index'
  get 'welcome/about'
  root 'users#show'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @user = User.find(current_user.id)
    @item = Item.new( { name: params[:item][:name], user_id: current_user.id } )

    @item.save
    redirect_to user_path(@user.id)
  end

  def destroy
    @user = User.find(params[:user_id])
    @item = Item.find(params[:id])
    @item.destroy

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id] || current_user.id)
    @items = @user.items
    @item = Item.new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<%= form_for [user, item] do |f| %>
  <div class="form-group">
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter new task" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<tbody id='item-<%= item.id %>'>
  <tr>
    <td class="check"><%= link_to "", user_item_path(@user.id, item.id), method: :delete, class: 'glyphicon glyphicon-ok', remote: true %></td>
    <td><%= item.name %></td>
    <td><%= distance_of_time_in_words(item.created_at + 7.days, Time.now) %> remaining</td>
  </tr>
</tbody>

app/views/items/destroy.js.erb
$('#item-<%= @item.id %>').fadeOut();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>alldone</title>
  <meta name="viewport" content="width=device-width, iniial-scale=1">
  <%= stylesheet_link_tag    'application', "https://fonts.googleapis.com/css?family=Varela+Round", "https://fonts.googleapis.com/css?family=PT+Sans", media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag %>
</head>
<body>
  <ul class="nav nav-tabs styled-font">
    <li><%= link_to "all done", root_path %></li>
    <div class="pull-right user-info">
      <% if user_signed_in? %>
        <li>Signed in as: <strong><%= current_user.email %></strong> |</li>
        <li><%= link_to 'Edit profile', edit_user_registration_path%> - </li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete  %></li>
      <% else %>
      <!-- # #2 display Sign Up and Sign In buttons if the user is not logged in-->
        <li><%= link_to "Sign Up", new_user_registration_path %> -
        <%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </div>
  </ul>
  </div>
  <%= yield %>
</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.erb
<div class="container todolist">
  <body class="list-background">
    <div class>
      <h1>What will you accomplish today?</h1>
      <table>
        <tr>
          <th></th>
          <th>Description</th>
          <th>Days Left</th>
        </tr>
        <% @items.each do |item| %>
          <%= render item %>
        <% end %>
      </table>
        <!-- <%= link_to "New Task", new_user_item_path(current_user), class: 'btn btn-success' %> -->
        <%= render 'items/form', item: Item.new, user: @user %>
    </div>
  </body>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>